### PR TITLE
Add support for fallback english translations

### PR DESCRIPTION
**Pull request by budziam**
It fixes bug that looks like this:

**GIVEN**

User has locale: **pl**

In translations.callpage.io there are english translations
```
[
  'q' => [
    'a' => 'foo'
  ]
]
```

In translations.callpage.io there are polish translations
```
[
  'q' => [
    'a' => 'bar'
  ]
]
```

English languages file
```
[
  'q' => [
    'b' => 'my-translation'
  ]
]
```

Polish languages file
```
[
  'q' => [
    'a' => 'foobar'
  ]
]
``` 

**WHEN**
User wants to translate `trans('q')`

**THEN**
Translation returns `['a' => 'bar']` instead of `['a' => 'bar', 'b' => 'my-translation']`

### CODE REVIEW

**Comment by Danonk** [comment]
What do you mean English languages file?

**Comment by budziam** [comment]
Translations located here: core/lang/en/....

**Comment by Danonk** [comment]
Why do you still want to use those?

**Comment by budziam** [comment]
Cause there are some translations in `en` folder that are not in `pl` folder nor in `translation.callpage.io`

**Comment by Danonk** [comment]
So we should move those translations to `translation.callpage.io`, and not make a walkaround for this. Right?

**Comment by budziam** [comment]
Yes, and you were to do it about 7 days ago. But you still did not do it, so I had to do a workaround :)

**Pull request merged**
